There are "Canvas with Errors" and "Form with Errors" When tested on Nokia emulator and Nokia 6230  I got "Allocation Error" and application will close! Application continue to run in WTK. Application continue to run on Moto V360.
Test with loading Classes from Package javax.microedition.io.newjsr included in Midlet..   "OverrideNewJSR" Test
java/lang/NoClassDefFoundError On WTK and Nokia
Application will crash on Moto V360

So it is safe to assume that our class loader will not allow classes from Packages
javax. and  javax.microedition.